# Generated by Django 6.0.5 on 2026-05-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("codigo", models.CharField(blank=True, max_length=20)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("ects", models.IntegerField()),
                ("descricao", models.TextField(blank=True)),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True, related_name="ucs", to="portfolio.docente"
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ucs",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
