# Generated by Django 6.0.5 on 2026-05-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_unidadecurricular"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("link_website", models.URLField(blank=True)),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        choices=[
                            (1, "Iniciante"),
                            (2, "Básico"),
                            (3, "Intermédio"),
                            (4, "Avançado"),
                            (5, "Especialista"),
                        ],
                        default=3,
                    ),
                ),
                ("categoria", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
