# Generated by Django 6.0.5 on 2026-05-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_formacao_competencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data", models.DateField()),
                (
                    "fotografia",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("erros_encontrados", models.TextField(blank=True)),
                ("decisoes_tomadas", models.TextField(blank=True)),
                ("uso_ia", models.TextField(blank=True)),
                ("entidade_relacionada", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
