# Generated by Django 6.0.5 on 2026-05-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_makingof"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                (
                    "projetos",
                    models.ManyToManyField(
                        blank=True, related_name="interesses", to="portfolio.projeto"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="interesses", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
    ]
